service: notes-http
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: 
            Fn::GetAtt:
              - NotesTable
              - Arn 

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  fetchNotes:
    handler: src/notes/fetchNotes.handler
    events:
      - httpApi:
          path: /notes
          method: get

  fetchNote:
    handler: src/notes/fetchNote.handler
    events:
      - httpApi:
          path: /note/{id}
          method: get

  addNote:
    handler: src/notes/addNote.handler
    events:
      - httpApi:
          path: /note
          method: post 

  updateNote:
    handler: src/notes/updateNote.handler
    events:
      - httpApi:
          path: /note/{id}
          method: put          

  deleteNote:
    handler: src/notes/deleteNote.handler
    events:
      - httpApi:
          path: /note/{id}
          method: delete

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NotesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH